# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_espectral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='firma_espectral',
            options={'verbose_name_plural': 'Firma Espectral'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name_plural': 'Taxon'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaci\xf3n'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_cielo',
            field=models.ImageField(upload_to='media/cielo/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_individuo',
            field=models.ImageField(upload_to='media/individuo/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_panorama',
            field=models.ImageField(upload_to='media/panorama/'),
        ),
    ]
